#
# (C) Copyright 2015 Intel
#
# (C) Copyright 2000-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += reset.o

#obj-$(CONFIG_TARGET_AXM5600) += axm5600/
#obj-$(CONFIG_TARGET_AXC6700) += axc6700/
