PLATFORM_RELFLAGS += -fno-strict-aliasing -Werror

ifdef CROSS_LIBS
PLATFORM_LDFLAGS += -L $(CROSS_LIBS)
endif

ifdef AXXIA_VERSION
KBUILD_CFLAGS += -DAXXIA_VERSION='"$(AXXIA_VERSION)"'
endif

ifdef AXXIA_ATF_VERSION
KBUILD_CFLAGS += -DAXXIA_ATF_VERSION='"$(AXXIA_ATF_VERSION)"'
endif