	#; ------------------------------------------------------------
	#; ------------------------------------------------------------
	#;
	#; (C) Copyright 2010 LSI Corporation
	#;
	#; This program is free software; you can redistribute it
	#; and/or modify it under the terms of the GNU General Public
	#; License as published by the Free Software Foundation; either
	#; version 2 of the License, or (at your option) any later
	#; version.
	#;
	#; This program is distributed in the hope that it will be
	#; useful, but WITHOUT ANY WARRANTY; without even the implied
	#; warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
	#; PURPOSE.  See the GNU General Public License for more
	#; details.
	#;
	#; You should have received a copy of the GNU General Public
	#; License along with this program; if not, write to the Free
	#; Software Foundation, Inc., 59 Temple Place, Suite 330,
	#; Boston, MA 02111-1307 USA
	#;
	#; ------------------------------------------------------------
	#; ------------------------------------------------------------

	.section	ose_strings_0_section
	.fill		0x400,1,0

	.section	ose_strings_1_section
	.fill		0x400,1,0

	.section	ose_strings_2_section
	.fill		0x400,1,0

	.section	ose_strings_3_section
	.fill		0x400,1,0

	.section	acp_osg_cores_section
	.fill		0x100,1,0

	.section	acp_osg_groups_section
	.fill		0x100,1,0

	.section	acp_system_section
	.fill		0x100,1,0
