/**************************************************************************
 **                                                                       *
 **    Copyright (c) 2001-2015, Intel Corporation.                        *
 **                                                                       *
 **************************************************************************/



#ifndef _NCP_TMGR_SYSTEM_COUNT_REG_DEFINES_H_
#define _NCP_TMGR_SYSTEM_COUNT_REG_DEFINES_H_

#ifdef __cplusplus
extern "C" {
#endif

    /* NODE 0x19 , TARGET 0x12*/


#define     NCP_TMGR_SYSTEM_COUNT_STAT_APB_BRIDGE               (0x00000000)
#define     NCP_TMGR_SYSTEM_COUNT_CFG_SYSTEM_COUNTER_CONTROL    (0x00000114)
#define     NCP_TMGR_SYSTEM_COUNT_CFG_BOOT2NUEVO_OFFSET         (0x00000118)
#define     NCP_TMGR_SYSTEM_COUNT_CFG_BOOT2NUEVO_SM             (0x0000011c)
#define     NCP_TMGR_SYSTEM_COUNT_GEN_INCR_INT_BOOT_COUNTER     (0x00000248)
#define     NCP_TMGR_SYSTEM_COUNT_CFG_SCM_FORCESYNC_CONTROL     (0x00000270)
#define     NCP_TMGR_SYSTEM_COUNT_TSG_CARRY_125_FIFO_STAT       (0x00000930)
#define     NCP_TMGR_SYSTEM_COUNT_TSG_CARRY_125_FIFO_WM         (0x00000934)
#define     NCP_TMGR_SYSTEM_COUNT_TSG_CARRY_125_FIFO_PUSH_STATE  (0x00000b60)
#define     NCP_TMGR_SYSTEM_COUNT_BOOT_COUNTER_XFER_STATE       (0x00000b64)

/* 5500 and 5600 */
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_BASE      (0x00020000)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM(n)        (0x00020000 + (4*(n)))
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_COUNT     (0x00000010)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_IDX(addr) \
  (((addr) - NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_BASE) / 4)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_END       (0x00020040)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_RANGE(addr) \
 (((addr) >= NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_BASE) && \
  ((addr) < NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_END))


#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_XLF_BASE  (0x00020000)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_XLF(n)    (0x00020000 + (4*(n)))
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_XLF_COUNT  (0x00000021)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_XLF_IDX(addr) \
  (((addr) - NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_XLF_BASE) / 4)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_XLF_END   (0x00020084)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_XLF_RANGE(addr) \
 (((addr) >= NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_XLF_BASE) && \
  ((addr) < NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_DELTA_RAM_XLF_END))

#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_ENABLE              (0x00020200)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_ENABLE_5600         (0x00020f00)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_ENABLE_XLF          (0x00020f00)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_ENABLE1_5600        (0x00020f04)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_ENABLE1_XLF         (0x00020f04)
#define     NCP_TMGR_SYSTEM_COUNT_GEN_INCR_FRAC_BOOT_COUNTER    (0x00000240)
#define     NCP_TMGR_SYSTEM_COUNT_GEN_INCR_FRAC_BOOT_COUNTER_ACCESS_SIZE  (0x00000008) /* Bytes */
#define     NCP_TMGR_SYSTEM_COUNT_GEN_INCR_FRAC_DEN_BOOT_COUNTER  (0x00000250)
#define     NCP_TMGR_SYSTEM_COUNT_GEN_INCR_FRAC_DEN_BOOT_COUNTER_ACCESS_SIZE  (0x00000008) /* Bytes */
#define     NCP_TMGR_SYSTEM_COUNT_BOOT_COUNTER                  (0x00000260)
#define     NCP_TMGR_SYSTEM_COUNT_BOOT_COUNTER_ACCESS_SIZE      (0x00000008) /* Bytes */
#define     NCP_TMGR_SYSTEM_COUNT_CAPTURED_BOOT_COUNTER         (0x00000280)
#define     NCP_TMGR_SYSTEM_COUNT_CAPTURED_BOOT_COUNTER_ACCESS_SIZE  (0x00000008) /* Bytes */


#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_BASE            (0x00020080)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM(n)              (0x00020080 + (8*(n)))
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_ACCESS_SIZE     (0x00000008) /* Bytes */
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_COUNT           (0x00000010)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_IDX(addr) \
    (((addr) - NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_BASE) / 8)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_END             (0x00020100)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_RANGE(addr) \
 (((addr) >= NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_BASE) && \
  ((addr) < NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_END))



#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_5600_BASE       (0x00020400)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_5600(n)         (0x00020400 + (8*(n)))
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_5600_ACCESS_SIZE  (0x00000008) /* Bytes */
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_5600_COUNT      (0x00000010)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_5600_IDX(addr) \
  (((addr) - NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_5600_BASE) / 8)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_5600_END        (0x00020480)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_5600_RANGE(addr) \
 (((addr) >= NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_5600_BASE) && \
  ((addr) < NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_5600_END))



#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_XLF_BASE        (0x00020400)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_XLF(n)          (0x00020400 + (8*(n)))
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_XLF_ACCESS_SIZE  (0x00000008) /* Bytes */
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_XLF_COUNT       (0x00000021)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_XLF_IDX(addr) \
  (((addr) - NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_XLF_BASE) / 8)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_XLF_END         (0x00020508)
#define     NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_XLF_RANGE(addr) \
 (((addr) >= NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_XLF_BASE) && \
  ((addr) < NCP_TMGR_SYSTEM_COUNT_CPU_TIMER_RAM_XLF_END))

#ifdef __cplusplus
}
#endif

#endif /* _NCP_TMGR_SYSTEM_COUNT_REG_DEFINES_H_ */
